version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20

  # Maintain dependencies for main repository
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20

  # Maintain dependencies for apps
  - package-ecosystem: 'npm'
    directory: '/apps'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20

  # Maintain dependencies for packages
  - package-ecosystem: 'npm'
    directory: '/packages'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20
