version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    ignore:
      - dependency-name: "@adiwajshing/libsignal-node"
      - dependency-name: "@whiskeysockets/baileys"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 30
