version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20

  # Maintain dependencies for main repository
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20

  # Maintain dependencies for api apps
  - package-ecosystem: 'npm'
    directory: '/apps/api'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20

  # Maintain dependencies for web apps
  - package-ecosystem: 'npm'
    directory: '/apps/web'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20

  # Maintain dependencies for database packages
  - package-ecosystem: 'npm'
    directory: '/packages/database'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20

  # Maintain dependencies for whatsapp packages
  - package-ecosystem: 'npm'
    directory: '/packages/whatsapp'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20
