name: Test Code and lint code
on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request_target:
    branches:
      - master

permissions:
  contents: write

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_KEY }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          run_install: true

      - name: Lint code
        run: pnpm run lint
